# Generated by Django 5.2.4 on 2025-07-17 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_queries', models.IntegerField(default=0)),
                ('successful_queries', models.IntegerField(default=0)),
                ('failed_queries', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(blank=True, null=True)),
                ('avg_relevance_score', models.FloatField(blank=True, null=True)),
                ('avg_context_chunks', models.FloatField(blank=True, null=True)),
                ('queries_by_language', models.JSONField(default=dict)),
                ('avg_user_rating', models.FloatField(blank=True, null=True)),
                ('avg_response_relevance', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('sw', 'Swahili'), ('am', 'Amharic')], max_length=5)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('response_text', models.TextField()),
                ('response_time_ms', models.IntegerField()),
                ('context_chunks_found', models.IntegerField()),
                ('avg_relevance_score', models.FloatField(blank=True, null=True)),
                ('max_relevance_score', models.FloatField(blank=True, null=True)),
                ('min_relevance_score', models.FloatField(blank=True, null=True)),
                ('embedding_time_ms', models.IntegerField(blank=True, null=True)),
                ('search_time_ms', models.IntegerField(blank=True, null=True)),
                ('llm_time_ms', models.IntegerField(blank=True, null=True)),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('response_relevance', models.IntegerField(blank=True, choices=[(1, 'Not Relevant'), (2, 'Somewhat Relevant'), (3, 'Relevant'), (4, 'Very Relevant'), (5, 'Highly Relevant')], null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='core_queryl_timesta_8f57b6_idx'), models.Index(fields=['language'], name='core_queryl_languag_c9076d_idx'), models.Index(fields=['avg_relevance_score'], name='core_queryl_avg_rel_cc2270_idx')],
            },
        ),
    ]
