# Generated by Django 5.2.4 on 2025-07-18 16:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemperformancemetrics_querylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='regeneration_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('copy', 'Copy Message'), ('regenerate', 'Regenerate Response'), ('rating', 'Rate Response'), ('follow_up', 'Follow-up Question')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('query_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.querylog')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
