# Generated by Django 5.2.4 on 2025-07-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_querylog_regeneration_count_useraction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadeddocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='author',
            field=models.CharField(blank=True, help_text='Author or organization', max_length=200),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='category',
            field=models.CharField(choices=[('internet_freedom', 'Internet Freedom'), ('accessibility', 'Accessibility'), ('gender_violence', 'Technology Facilitated Gender-Based Violence'), ('digital_inclusion', 'Digital Inclusion'), ('policy_governance', 'Policy & Governance'), ('cybersecurity', 'Cybersecurity'), ('data_protection', 'Data Protection & Privacy'), ('digital_economy', 'Digital Economy'), ('education_literacy', 'Digital Education & Literacy'), ('infrastructure', 'Digital Infrastructure'), ('research_reports', 'Research & Reports'), ('legal_frameworks', 'Legal Frameworks'), ('other', 'Other')], default='other', help_text='Document category', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the document content'),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='document_type',
            field=models.CharField(choices=[('report', 'Report'), ('policy', 'Policy Document'), ('research', 'Research Paper'), ('guideline', 'Guidelines'), ('case_study', 'Case Study'), ('presentation', 'Presentation'), ('manual', 'Manual/Handbook'), ('legislation', 'Legislation'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='geographic_scope',
            field=models.CharField(blank=True, help_text="Geographic coverage (e.g., 'Kenya', 'East Africa', 'Global')", max_length=100),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Whether document has been embedded'),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='processing_notes',
            field=models.TextField(blank=True, help_text='Notes about processing or any issues'),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='publication_date',
            field=models.DateField(blank=True, help_text='Original publication date', null=True),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='source',
            field=models.CharField(blank=True, help_text='Source organization or publisher', max_length=200),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='target_audience',
            field=models.CharField(blank=True, help_text='Intended audience', max_length=200),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='title',
            field=models.CharField(blank=True, help_text='Document title', max_length=300),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['category'], name='core_upload_categor_54a067_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['language'], name='core_upload_languag_4afca5_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['uploaded_at'], name='core_upload_uploade_dc934f_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['is_processed'], name='core_upload_is_proc_15716d_idx'),
        ),
    ]
